global:
  #relevant directories
  PATH_PIPE: /home/cornisht/LSST_clustering/pHSC3/
  PATH_DATA: /home/cornisht/LSST_clustering/Data/HSC_DR3/
  PATH_OUT: /home/cornisht/LSST_clustering/pHSC3/out/
  PATH_PLOTS: /home/cornisht/LSST_clustering/pHSC3/out/figures/

  #data release
  dr: pdr3_wide

  #fields to run
  fields: [hectomap]

  #NSIDE parameter for the low- and high-resolution components of the maps
  nside_lo: 32
  nside_hi: 1024
  #low-resolution NSIDE parameter to use for splitting the data
  nside_cover: 8

  #main photometric band
  band: i
  #list of all photometric bands
  bands: [g, r, i, z, y]
  #alternative names for some bands
  bands_alt:
    i: [i2]
    r: [r2]

  #S/N thresholds in primary band and other bands
  sn_pri: 10.
  sn_sec: 5.
  #depth limit in primary band
  depth_cut: 24.5

  #threshold below which pixels in the survey mask will be considered masked
  weight_thresh: 0.5
  #whether to smooth the mask
  smooth_mask: true
  #width (in arcmin) of the smoothing kernel
  smooth_fwhm: 60.
  #threshold to apply to smoothed mask
  smooth_thresh: 0.4

  #catalogue names
  cat_basic: basicclean_catalogue.hdf5
  cat_main: clean_catalogue.hdf5
  cat_stars: star_catalogue.hdf5

  #names for various maps
  dustmaps:
  - dustmaps_g_1024.hsp
  - dustmaps_r_1024.hsp
  - dustmaps_i_1024.hsp
  - dustmaps_z_1024.hsp
  - dustmaps_y_1024.hsp
  footprint: footprint_1024.hsp
  bo_mask: bo_mask_1024.hsp
  masked_frac: masked_fraction_1024.hsp
  survey_mask: survey_mask_1024.hsp
  star_map: star_counts_1024.hsp
  depth_map: depth_map_1024.hsp
  ngal_maps: ngal_maps_1024.hsp
  deltag_maps: deltag_maps_1024.hsp

  #redshift column to use for tomography
  zcol: pz_best_dnnz
  #redshift bin edges
  zbins: [0.3, 0.6, 0.9, 1.2, 1.5]
  nbins: 4

