global:
  #relevant directories
  paths:
    pipeline: /home/cornisht/LSST_clustering/pHSC3/
    data: /home/cornisht/LSST_clustering/Data/HSC_DR3/
    out: /home/cornisht/LSST_clustering/pHSC3/out/
    figures: /home/cornisht/LSST_clustering/pHSC3/out/figures/
  
  #column names corresponding to key quantities in the catalogue
  key_cols:
    zphot: pz_best_dnnz
    mag: cmodel_mag

  #data release
  dr: pdr3_wide

  #fields to run
  fields: [hectomap]

  #NSIDE parameter for the low- and high-resolution components of the maps
  nside_lo: 32
  nside_hi: 1024
  #low-resolution NSIDE parameter to use for splitting the data
  nside_cover: 8

  #photometric bands
  bands:
    #main band
    primary: i
    #list of all other bands
    secondary: [g, r, z, y]
    #alternative names for some bands
    altnames:
      i: [i2]
      r: [r2]

  #S/N thresholds in primary band and other bands
  sn_pri: 10.
  sn_sec: 5.
  #depth limit in primary band
  depth_cut: 24.5

  #threshold below which pixels in the survey mask will be considered masked
  weight_thresh: 0.5
  #whether to smooth the mask
  smooth_mask: true
  #width (in arcmin) of the smoothing kernel
  smooth_fwhm: 60.
  #threshold to apply to smoothed mask
  smooth_thresh: 0.4

  #suffix to add to filenames produced from this run
  suffix: ''

  #catalogue names (without file extensions)
  cats:
    basic: basicclean_catalogue
    main: clean_catalogue
    stars: star_catalogue

  #base names for various maps (without file extensions)
  maps:
    dustmaps: dustmaps
    footprint: footprint
    bo_mask: bo_mask
    masked_frac: masked_fraction
    survey_mask: survey_mask
    star_map: star_counts
    depth_map: depth_map
    ngal_maps: ngal_maps
    deltag_maps: deltag_maps
