###########################################################################################

global:
  #relevant directories
  paths:
    pipeline: /home/cornisht/LSST_clustering/pHSC3/
    data: /home/cornisht/LSST_clustering/Data/HSC_DR3/
    out: /home/cornisht/LSST_clustering/pHSC3/out/
    figures: /home/cornisht/LSST_clustering/pHSC3/out/figures/
  
  #column names corresponding to key quantities in the catalogue
  key_cols:
    zphot: pz_best_dnnz
    mag: cmodel_mag

  #data release
  dr: pdr3_wide

  #fields to run
  fields: [hectomap]

  #NSIDE parameter for the low- and high-resolution components of the maps
  nside_lo: 32
  nside_hi: 1024
  #low-resolution NSIDE parameter to use for splitting the data
  nside_cover: 8

  #photometric bands
  bands:
    #main band
    primary: i
    #list of all other bands
    secondary: [g, r, z, y]
    #alternative names for some bands
    altnames:
      i: [i2]
      r: [r2]

  #S/N thresholds in primary band and other bands
  sn_pri: 10.
  sn_sec: 5.
  #depth limit in primary band
  depth_cut: 24.5

  #threshold below which pixels in the survey mask will be considered masked
  weight_thresh: 0.5
  #whether to smooth the mask
  smooth_mask: true
  #width (in arcmin) of the smoothing kernel
  smooth_fwhm: 60.
  #threshold to apply to smoothed mask
  smooth_thresh: 0.4

  #suffix to add to filenames produced from this run
  suffix: ''

  #catalogue names (without file extensions)
  cats:
    basic: basicclean_catalogue
    main: clean_catalogue
    stars: star_catalogue

  #base names for various maps (without file extensions)
  maps:
    dustmaps: dustmaps
    footprint: footprint
    bo_mask: bo_mask
    masked_frac: masked_fraction
    survey_mask: survey_mask
    star_map: star_counts
    depth_map: depth_map
    ngal_maps: ngal_maps
    deltag_maps: deltag_maps

  #auxiliary pipeline files
  auxfiles:
    required_cols: required_cols.txt
    decasu_config: decasu_config_hpix_hsc_dr3.yaml

  #tomographic sample definitions (semi-colon separated)
  samples:
    bin0: '0.3 <= zphot ; zphot < 0.6'
    bin1: '0.6 <= zphot ; zphot < 0.9'
    bin2: '0.9 <= zphot ; zphot < 1.2'
    bin3: '1.2 <= zphot ; zphot < 1.5'

###########################################################################################

getData:
  #submit/download data requests
  submit: true
  download: true
  #include photo-z information
  photoz: true
  #include stellar masses and SFRs from MIZUKI
  mizuki_mstar_sfrs: true
  #apply cuts based on existing flags in the catalogues
  apply_cuts: false
  strict_cuts: false

  #maximum number of sources allowed before catalogues split for field
  Nmax: 5_000_000

###########################################################################################

splitMetadata:
  #boundaries of each global field, ordered [RA_min, RA_max, DEC_min, DEC_max]
  bounds:
    aegis: [212., 216., 51.6, 53.6]
    spring: [326.25, 41.25, -8., 8.]
    autumn: [125., 227.5, -4., 7.]
    hectomap: [195., 255., 41.5, 45.]

  #whether to further split the metadata by filter (can help Decasu avoid memory issues)
	split_by_band: true

###########################################################################################

cleanCats:
  #types of flag to apply during basic cleaning (list containing 'main' and/or 'strict' or empty)
  remove_if_flagged: [main]
  #logged blending cut (maximum allowed flux estimated to be from blending)
  log_blend_cut: -0.375
  #whether to correct recorded r/i photometry to equivalent in r2/i2
  correct_ri: true
  #whether to remove galaxies likely to have secondary redshift solutions at high-z
  remove_pz_outliers: true
  #file for containing a summary of each stage of cleaning
  clean_summary_file: cleaning_summary.txt

###########################################################################################

makeMapsFromMetadata:
  #number of cores to use for multiprocessing
  ncores: 18

###########################################################################################

makeMapsFromCat:
  #whether or not to initially make the map at high resolution and degrade
  highres_first: false
  #NSIDE for the upgraded-resolution version of the bright object mask
  nside_mask: 8192

  #types of flag to include in the mask 
  #(list containing 'brightstar', 'main' and/or 'strict; see flags.py for definitions)
  flags_to_mask: [brightstar]
  #whether or not to include the y-band channel stop in the brightstar flags
  incl_channelstop: false

  #if only stars should be used for creating depth map
  stars_for_depth: true
  #minimum number of sources required to calculate depth in a pixel
  min_sources: 4

  #radius (in deg) of the Guassian kernel used to smooth certain maps
  r_smooth: 2.

  #use N_exp maps to define an extra cut?
  use_nexp_maps: true

###########################################################################################
