outbase: 'decasu_2048'
nside: 2048
map_types:
  nexp: ['sum']
use_two_amps: False
arcsec_per_pix: 0.17
maglim_aperture: 4.08
maglim_nsig: 5.0
zp_global: 27.0
magzp_field: "zeropt"
exp_field: "visit"
ccd_field: "ccd"
band_field: "filter"
mjd_field: "mjd"
skyvar_field: "skylevel"
bad_amps: {}
bad_ccds: [9]
extra_fields: {}
band_replacement: {'i2': 'i', 'r2': 'r'}
use_wcs: False
ra_corner_fields: ['llcra', 'lrcra', 'urcra', 'ulcra']
dec_corner_fields: ['llcdec', 'lrcdec', 'urcdec', 'ulcdec']
latitude: 19.8230
longitude: -155.4694
elevation: 4205.0