outbase: 'decasu_512'
nside: 512
map_types:
  nexp: ['sum']
  exptime: ['sum']
  ccdtemp: ['mean']
  airmass: ['mean', 'min', 'max']
  seeing: ['mean']
  maglim: ['wmean']
  dcr_dra: ['mean']
  dcr_ddec: ['mean']
  dcr_e1: ['mean']
  dcr_e2: ['mean']
  sigma_sky: ['mean']
  skylevel: ['mean', 'mean-scaled']
  ellipticity: ['mean']
  weight: ['sum']
use_two_amps: False
arcsec_per_pix: 0.17
maglim_aperture: 4.08
maglim_nsig: 5.0
zp_global: 27.0
magzp_field: "zeropt"
exp_field: "visit"
ccd_field: "ccd"
band_field: "filter"
mjd_field: "mjd"
skyvar_field: "skylevel"
bad_amps: {}
bad_ccds: [9]
extra_fields: {}
band_replacement: {'i2': 'i', 'r2': 'r'}
use_wcs: False
ra_corner_fields: ['llcra', 'lrcra', 'urcra', 'ulcra']
dec_corner_fields: ['llcdec', 'lrcdec', 'urcdec', 'ulcdec']
latitude: 19.8230
longitude: -155.4694
elevation: 4205.0